spring:
  mvc:
    problemdetails:
      enabled: true
  config:
    import: "classpath:application-persistence.yml"
  application:
    name: Nyounda-api
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB