spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nyounda
    username: nyoundauser
    password: nyoundauser
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default-schema: public
logging:
  level:
    liquibase: DEBUG
