### Authenticate Phone Number
GET {{host}}/authenticate?phone={{phoneNumber}}&channel={{channel}}
Content-Type: application/json
Accept: application/json

### Verify Phone Number
POST {{host}}/verify
Content-Type: application/json
Accept: application/json

{
  "phone": "{{phoneNumber}}",
  "pinCode": "{{pinCode}}",
  "locale": "{{locale}}"
}