### Authenticate Phone Number
GET {{host}}/authenticate?phone={{phoneNumber}}&channel={{channel}}
Content-Type: application/json
Accept: application/json

### Verify Phone Number
GET {{host}}/verify?phone={{phoneNumber}}&pinCode={{pinCode}}&locale={{locale}}
Content-Type: application/json
Accept: application/json