### Authenticate Phone Number
GET {{host}}/authenticate?phonbbe={{phoneNumber}}&channel={{channel}}
Content-Type: application/json
Accept: application/json

### Verify Phone Number
GET {{host}}/verify?phone={{phoneNumber}}&token={{token}}&locale={{locale}}
Content-Type: application/json
Accept: application/json

### Test
GET {{host}}/test